// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsCptdykgPVfLfGGa6mWTEhF9d5B3G4LA',
    appId: '1:697693205362:web:086d5e144161c1c4d1e3eb',
    messagingSenderId: '697693205362',
    projectId: 'test-54168',
    authDomain: 'test-54168.firebaseapp.com',
    storageBucket: 'test-54168.firebasestorage.app',
    measurementId: 'G-M7651DW36J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-iv9T-sC8PDxCk3MDzSHn8l7DPttZXXY',
    appId: '1:697693205362:android:a412f206cecbfc26d1e3eb',
    messagingSenderId: '697693205362',
    projectId: 'test-54168',
    storageBucket: 'test-54168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3-nrFzkAuAaOoMkYElQhrvOLaMq9kg8',
    appId: '1:697693205362:ios:f4f9fd56a1a595cbd1e3eb',
    messagingSenderId: '697693205362',
    projectId: 'test-54168',
    storageBucket: 'test-54168.firebasestorage.app',
    iosBundleId: 'com.example.telwareCrossPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe3-nrFzkAuAaOoMkYElQhrvOLaMq9kg8',
    appId: '1:697693205362:ios:f4f9fd56a1a595cbd1e3eb',
    messagingSenderId: '697693205362',
    projectId: 'test-54168',
    storageBucket: 'test-54168.firebasestorage.app',
    iosBundleId: 'com.example.telwareCrossPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsCptdykgPVfLfGGa6mWTEhF9d5B3G4LA',
    appId: '1:697693205362:web:55743562aaf79a55d1e3eb',
    messagingSenderId: '697693205362',
    projectId: 'test-54168',
    authDomain: 'test-54168.firebaseapp.com',
    storageBucket: 'test-54168.firebasestorage.app',
    measurementId: 'G-5P1R0BX6NC',
  );
}
